[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_DISCORD_CLIENT_ID = "1407945986424307713"
  # Add your actual Discord Client ID here when you have it
  # VITE_SUPABASE_URL = "your_supabase_url_here"
  # VITE_SUPABASE_ANON_KEY = "your_supabase_key_here"